# REDIS
redis:
    image: redis
    ports:
        - "6379:6379"

# MONGODB
mongodb:
    image: mongodb
    ports:
        - "27017:27017"

# NODE
node:
  build: ./node
  links:
    - redis:redis
    - mongodb:mongodb
  ports:
    - "8080:8080"
  volumes:
    - ./app:/var/www/html
  tty: true

# NGINX
nginx:
  restart: always
  image: nginx
  ports:
    - "80:80"
  links:
    - node:node
  volumes:
    - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    - ./log/nginx:/var/log/nginx

